Proxysql job is failing in compilation phase due to below error (#1689)
fatal error: 'uuid/uuid.h' file not found

Added library:
For CentOS: libuuid libuuid-devel
For Ubuntu: uuid-dev